# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'seungpils-blog'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu:
  - name: Posts
    link: /
    
